fragment AavegotchiInfo on Aavegotchi {
  activeListing
  baseRarityScore
  claimedAt
  claimedTime
  collateral
  createdAt
  equippedWearables
  equippedDelegatedWearables
  escrow
  experience
  gotchiId
  hauntId
  historicalPrices
  id
  kinship
  lending
  level
  locked
  minimumStake
  modifiedNumericTraits
  modifiedRarityScore
  name
  numericTraits
  stakedAmount
  timesTraded
  status
  toNextLevel
  usedSkillPoints
  withSetsNumericTraits
  withSetsRarityScore
  lastInteracted
  equippedSetID
  equippedSetName
  equippedDelegatedWearables
  owner {
    id
  }
  originalOwner {
    id
  }
}

fragment ItemTypeInfo on ItemType {
  name
}

query GetAavegotchis(
  $first: Int
  $orderBy: Aavegotchi_orderBy
  $orderDirection: OrderDirection
  $where: Aavegotchi_filter
) {
  aavegotchis(first: $first, orderBy: $orderBy, orderDirection: $orderDirection, where: $where) {
    ...AavegotchiInfo
  }
}

query GetAavegotchisPaginated(
  $first: Int!
  $skip: Int!
  $orderBy: Aavegotchi_orderBy
  $orderDirection: OrderDirection
) {
  aavegotchis(first: $first, skip: $skip, orderBy: $orderBy, orderDirection: $orderDirection) {
    id
    name
    createdAt
    historicalPrices
    timesTraded
    activeListing
  }
}

query GetPortalsPaginated(
  $first: Int!
  $skip: Int!
  $orderBy: Portal_orderBy
  $orderDirection: OrderDirection
) {
  portals(first: $first, skip: $skip, orderBy: $orderBy, orderDirection: $orderDirection) {
    id
    gotchiId
    buyer {
      id
    }
    hauntId
    owner {
      id
    }
    options(first: 10) {
      id
      portalOptionId
      randomNumber
      numericTraits
      collateralType
      minimumStake
      baseRarityScore
    }
    status
    boughtAt
    openedAt
    claimedAt
    claimedTime
    timesTraded
    historicalPrices
    activeListing
  }
}
